x-test-name: &test-name control-test-update-aikido
x-test-token: &test-token AIK_RUNTIME_1_control-test-update-aikido
x-app-service: &app-service app-control-test-update-aikido
x-database-name: &database-name control-test-update-aikido

services:
  setup-control-test-update-aikido:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: setup-template
    environment:
      TEST_NAME: *test-name
      TEST_TOKEN: *test-token

  app-control-test-update-aikido:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: app-template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: *test-token
      DATABASE_NAME: *database-name
      DATABASE_URL: '${DATABASE_URL_PREFIX:?Set DATABASE_URL_PREFIX}control-test-update-aikido${DATABASE_URL_SUFFIX:?Set DATABASE_URL_SUFFIX}'
    depends_on:
      setup-control-test-update-aikido:
        condition: service_completed_successfully

  control-test-update-aikido:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: test-template
    environment:
      TEST_NAME: *test-name
      TEST_TOKEN: *test-token
      TEST_SERVER_HOST: *app-service
      TEST_CONTROL_SERVER_HOST: *app-service
    depends_on:
      app-control-test-update-aikido:
        condition: service_started
