services:
  test-shell-injection:
    profiles:
      - attacks
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: app-template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: AIK_RUNTIME_1_test-shell-injection
      DATABASE_NAME: test-shell-injection
      DATABASE_URL:
        '${DATABASE_URL_PREFIX:?Set
        DATABASE_URL_PREFIX}test-shell-injection${DATABASE_URL_SUFFIX:?Set
        DATABASE_URL_SUFFIX}'
