x-test-name: &test_name control_test_start_stop
x-test-token: &test_token AIK_RUNTIME_1_control_test_start_stop
x-app-service: &app_service app_control_test_start_stop
x-database-name: &database_name control_test_start_stop

services:
  setup_control_test_start_stop:
    extends:
      file: ../compose.templates.${COMPOSE_OS:-linux}.yml
      service: setup_template
    environment:
      TEST_NAME: *test_name
      TEST_TOKEN: *test_token

  app_control_test_start_stop:
    extends:
      file: ../compose.templates.${COMPOSE_OS:-linux}.yml
      service: app_template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: *test_token
      DATABASE_NAME: *database_name
      DATABASE_URL: '${DATABASE_URL_PREFIX:-postgres://myuser:mysecretpassword@postgres:5432/}control_test_start_stop${DATABASE_URL_SUFFIX:-?sslmode=disable}'
    depends_on:
      setup_control_test_start_stop:
        condition: service_completed_successfully

  control_test_start_stop:
    extends:
      file: ../compose.templates.${COMPOSE_OS:-linux}.yml
      service: test_template
    environment:
      TEST_NAME: *test_name
      TEST_TOKEN: *test_token
      TEST_SERVER_HOST: *app_service
      TEST_CONTROL_SERVER_HOST: *app_service
    depends_on:
      app_control_test_start_stop:
        condition: service_started
