name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  dockerfile_path:
    description: The path to the Dockerfile with the Aikido agent installed
    required: true
  max_parallel_tests:
    description:
      The maximum number of tests to run in parallel (for each test, a new
      container will be spawned)
    required: true
    default: '5'

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  pre: pre.js
  main: dist/index.js
