name: Aikido Firewall Tester
description: Aikido Firewall Tester
author: AikidoSec

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  dockerfile_path:
    description: The path to the Dockerfile with the Aikido agent installed
    required: true
  extra_args:
    description:
      Extra arguments to pass to the docker run command (only --env, -e and
      --env-file are allowed)
    required: false
    default: ''
  extra_build_args:
    description:
      Extra arguments to pass to the docker build command (e.g. "--build-arg
      APP_VERSION=2.0.1")
    required: false
    default: ''
  app_port:
    description:
      The port of the application to test, the one that is open when docker is
      running
    required: true
    default: '8080'
  max_parallel_tests:
    description:
      The maximum number of tests to run in parallel (for each test, a new
      container will be spawned). Default is 10.
    required: true
    default: '10'
  config_update_delay:
    description:
      The delay in seconds to wait after updating the config to ensure the
      config is applied. Default is 60 seconds.
    required: true
    default: '60'
  skip_tests:
    description:
      Comma-separated list of test names to skip (e.g.
      "test_allowed_ip,test2,test3")
    required: false
    default: ''
  test_timeout:
    description: The timeout in seconds for each test. Default is 60 seconds.
    required: false
    default: '600'
  sleep_before_test:
    description:
      The number of seconds to sleep before starting the test. Default is 1
      second.
    required: false
    default: '1'
  ignore_failures:
    description:
      If true, the action will exit with code 0 even if tests fail. Default is
      false.
    required: false
    default: 'false'

runs:
  using: node20
  main: dist/index.js
