name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  dockerfile_path:
    description: The path to the Dockerfile with the Aikido agent installed
    required: true
  max_parallel_tests:
    description:
      The maximum number of tests to run in parallel (for each test, a new
      container will be spawned)
    required: true
    default: '5'
  config_update_delay:
    description:
      The delay in seconds to wait after updating the config to ensure the
      config is applied.
    required: true
    default: '60'
  skip_tests:
    description:
      Comma-separated list of test names to skip (e.g.
      "test_allowed_ip,test2,test3")
    required: false
    default: ''

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
