services:
  app-test-allowed-ip-for-routes:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: app-template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: AIK_RUNTIME_1_test-allowed-ip-for-routes
      DATABASE_NAME: test-allowed-ip-for-routes
      DATABASE_URL:
        '${DATABASE_URL_PREFIX:?Set
        DATABASE_URL_PREFIX}test-allowed-ip-for-routes${DATABASE_URL_SUFFIX:?Set
        DATABASE_URL_SUFFIX}'
