services:
  test-internet-not-available:
    profiles:
      - core-integration
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: app-template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: AIK_RUNTIME_1_test-internet-not-available
      DATABASE_NAME: test-internet-not-available
      DATABASE_URL:
        '${DATABASE_URL_PREFIX:?Set
        DATABASE_URL_PREFIX}test-internet-not-available${DATABASE_URL_SUFFIX:?Set
        DATABASE_URL_SUFFIX}'
