services:
  app-test-force-protection-off:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: app-template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: AIK_RUNTIME_1_test-force-protection-off
      DATABASE_NAME: test-force-protection-off
      DATABASE_URL:
        '${DATABASE_URL_PREFIX:?Set
        DATABASE_URL_PREFIX}test-force-protection-off${DATABASE_URL_SUFFIX:?Set
        DATABASE_URL_SUFFIX}'
