services:
  app-test-bypassed-ip-for-rate-limiting:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: app-template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: AIK_RUNTIME_1_test-bypassed-ip-for-rate-limiting
      DATABASE_NAME: test-bypassed-ip-for-rate-limiting
      DATABASE_URL:
        '${DATABASE_URL_PREFIX:?Set
        DATABASE_URL_PREFIX}test-bypassed-ip-for-rate-limiting${DATABASE_URL_SUFFIX:?Set
        DATABASE_URL_SUFFIX}'
