services:
  test-user-ip-from-proxy:
    profiles:
      - core-integration
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: app-template
    env_file:
      - ./test.env
    environment:
      AIKIDO_CLIENT_IP_HEADER: ${AIKIDO_CLIENT_IP_HEADER:-X-Real-IP}
      AIKIDO_TOKEN: AIK_RUNTIME_1_test-user-ip-from-proxy
      DATABASE_NAME: test-user-ip-from-proxy
      DATABASE_URL:
        '${DATABASE_URL_PREFIX:?Set
        DATABASE_URL_PREFIX}test-user-ip-from-proxy${DATABASE_URL_SUFFIX:?Set
        DATABASE_URL_SUFFIX}'
