services:
  test-allow-traffic-by-countries:
    profiles:
      - policies
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: app-template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: AIK_RUNTIME_1_test-allow-traffic-by-countries
      DATABASE_NAME: test-allow-traffic-by-countries
      DATABASE_URL:
        '${DATABASE_URL_PREFIX:?Set
        DATABASE_URL_PREFIX}test-allow-traffic-by-countries${DATABASE_URL_SUFFIX:?Set
        DATABASE_URL_SUFFIX}'
