services:
  test-wave-attack:
    profiles:
      - attacks
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: app-template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: AIK_RUNTIME_1_test-wave-attack
      DATABASE_NAME: test-wave-attack
      DATABASE_URL:
        '${DATABASE_URL_PREFIX:?Set
        DATABASE_URL_PREFIX}test-wave-attack${DATABASE_URL_SUFFIX:?Set
        DATABASE_URL_SUFFIX}'
