x-test-name: &test_name test_outbound_domain_blocking
x-test-token: &test_token AIK_RUNTIME_1_test_outbound_domain_blocking
x-app-service: &app_service app_test_outbound_domain_blocking
x-database-name: &database_name test_outbound_domain_blocking

services:
  setup_test_outbound_domain_blocking:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: setup_template
    environment:
      TEST_NAME: *test_name
      TEST_TOKEN: *test_token

  app_test_outbound_domain_blocking:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: app_template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: *test_token
      DATABASE_NAME: *database_name
      DATABASE_URL: '${DATABASE_URL_PREFIX:?Set DATABASE_URL_PREFIX}test_outbound_domain_blocking${DATABASE_URL_SUFFIX:?Set DATABASE_URL_SUFFIX}'
    depends_on:
      setup_test_outbound_domain_blocking:
        condition: service_completed_successfully
      mock_server_outbound_domain_blocking_test_outbound_domain_blocking:
        condition: service_started
    networks:
      - default
      - outbound_domain_blocking_test_outbound_domain_blocking

  test_outbound_domain_blocking:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: test_template
    environment:
      TEST_NAME: *test_name
      TEST_TOKEN: *test_token
      TEST_SERVER_HOST: *app_service
      TEST_CONTROL_SERVER_HOST: *app_service
    depends_on:
      app_test_outbound_domain_blocking:
        condition: service_started

  mock_server_outbound_domain_blocking_test_outbound_domain_blocking:
    image: ${PYTHON_MOCK_IMAGE:?Set PYTHON_MOCK_IMAGE}
    volumes:
      - type: bind
        source: ..
        target: ${PYTHON_SIDECAR_DIR:?Set PYTHON_SIDECAR_DIR}
        read_only: true
    command: python ${PYTHON_MOCK_HTTP_SERVER_PATH:?Set PYTHON_MOCK_HTTP_SERVER_PATH}
    environment:
      RESPONSE_BODY: '{"status":"ok"}'
    networks:
      outbound_domain_blocking_test_outbound_domain_blocking:
        ipv4_address: 11.22.33.44
        aliases:
          - evil.example.com
          - domain1.example.com
          - domain2.example.com
          - safe.example.com
          - another-unknown.example.com
          - unknown.example.com
          - xn--bse-sna.example.com
          - xn--mnchen-3ya.example.com
          - xn--mnchen-allowed-gsb.example.com

networks:
  outbound_domain_blocking_test_outbound_domain_blocking:
    ipam:
      config:
        - subnet: 11.22.33.0/24
