x-test-name: &test-name test-outbound-domain-blocking
x-test-token: &test-token AIK_RUNTIME_1_test-outbound-domain-blocking
x-app-service: &app-service app-test-outbound-domain-blocking
x-database-name: &database-name test-outbound-domain-blocking

services:
  setup-test-outbound-domain-blocking:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: setup-template
    environment:
      TEST_NAME: *test-name
      TEST_TOKEN: *test-token

  app-test-outbound-domain-blocking:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: app-template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: *test-token
      DATABASE_NAME: *database-name
      DATABASE_URL: '${DATABASE_URL_PREFIX:?Set DATABASE_URL_PREFIX}test-outbound-domain-blocking${DATABASE_URL_SUFFIX:?Set DATABASE_URL_SUFFIX}'
      APP_HOSTS_ENTRIES: >-
        11.22.33.44 böse.example.com|11.22.33.44 münchen.example.com|11.22.33.44 münchen-allowed.example.com
    depends_on:
      setup-test-outbound-domain-blocking:
        condition: service_completed_successfully
      mock-server-outbound-domain-blocking-test-outbound-domain-blocking:
        condition: service_started
    networks:
      - default
      - outbound-domain-blocking-test-outbound-domain-blocking

  test-outbound-domain-blocking:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: test-template
    environment:
      TEST_NAME: *test-name
      TEST_TOKEN: *test-token
      TEST_SERVER_HOST: *app-service
      TEST_CONTROL_SERVER_HOST: *app-service
    depends_on:
      app-test-outbound-domain-blocking:
        condition: service_started

  mock-server-outbound-domain-blocking-test-outbound-domain-blocking:
    image: ${PYTHON_MOCK_IMAGE:?Set PYTHON_MOCK_IMAGE}
    volumes:
      - type: bind
        source: ..
        target: ${PYTHON_SIDECAR_DIR:?Set PYTHON_SIDECAR_DIR}
        read_only: true
    command: python ${PYTHON_MOCK_HTTP_SERVER_PATH:?Set PYTHON_MOCK_HTTP_SERVER_PATH}
    environment:
      RESPONSE_BODY: '{"status":"ok"}'
    networks:
      outbound-domain-blocking-test-outbound-domain-blocking:
        ipv4_address: 11.22.33.44
        aliases:
          - evil.example.com
          - domain1.example.com
          - domain2.example.com
          - safe.example.com
          - another-unknown.example.com
          - unknown.example.com
          - böse.example.com
          - münchen.example.com
          - münchen-allowed.example.com
          - xn--bse-sna.example.com
          - xn--mnchen-3ya.example.com
          - xn--mnchen-allowed-gsb.example.com

networks:
  outbound-domain-blocking-test-outbound-domain-blocking:
    name: ${COMPOSE_PROJECT_NAME:-firewall-tester-action}-outbound-domain-blocking-test-outbound-domain-blocking
    ipam:
      config:
        - subnet: 11.22.33.0/24
