services:
  app-test-rate-limiting-group-id-1-minute:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: app-template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: AIK_RUNTIME_1_test-rate-limiting-group-id-1-minute
      DATABASE_NAME: test-rate-limiting-group-id-1-minute
      DATABASE_URL:
        '${DATABASE_URL_PREFIX:?Set
        DATABASE_URL_PREFIX}test-rate-limiting-group-id-1-minute${DATABASE_URL_SUFFIX:?Set
        DATABASE_URL_SUFFIX}'
