services:
  app-test-core-went-down:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: app-template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: AIK_RUNTIME_1_test-core-went-down
      DATABASE_NAME: test-core-went-down
      DATABASE_URL:
        '${DATABASE_URL_PREFIX:?Set
        DATABASE_URL_PREFIX}test-core-went-down${DATABASE_URL_SUFFIX:?Set
        DATABASE_URL_SUFFIX}'
