x-test-name: &test_name test_demo_apps_generic_tests
x-test-token: &test_token AIK_RUNTIME_1_test_demo_apps_generic_tests
x-app-service: &app_service app_test_demo_apps_generic_tests
x-database-name: &database_name test_demo_apps_generic_tests

services:
  setup_test_demo_apps_generic_tests:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: setup_template
    environment:
      TEST_NAME: *test_name
      TEST_TOKEN: *test_token

  app_test_demo_apps_generic_tests:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: app_template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: *test_token
      DATABASE_NAME: *database_name
      DATABASE_URL: '${DATABASE_URL_PREFIX:?Set DATABASE_URL_PREFIX}test_demo_apps_generic_tests${DATABASE_URL_SUFFIX:?Set DATABASE_URL_SUFFIX}'
    depends_on:
      setup_test_demo_apps_generic_tests:
        condition: service_completed_successfully

  test_demo_apps_generic_tests:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: test_template
    environment:
      TEST_NAME: *test_name
      TEST_TOKEN: *test_token
      TEST_SERVER_HOST: *app_service
      TEST_CONTROL_SERVER_HOST: *app_service
    depends_on:
      app_test_demo_apps_generic_tests:
        condition: service_started
