x-test-name: &test_name test_user_rate_limiting_1_minute_enable_disable
x-test-token: &test_token AIK_RUNTIME_1_test_user_rate_limiting_1_minute_enable_disable
x-app-service: &app_service app_test_user_rate_limiting_1_minute_enable_disable
x-database-url: &database_url 'postgres://${POSTGRES_USER:-myuser}:${POSTGRES_PASSWORD:-mysecretpassword}@postgres:5432/test_user_rate_limiting_1_minute_enable_disable?sslmode=disable'

services:
  setup_test_user_rate_limiting_1_minute_enable_disable:
    extends:
      file: ../compose.templates.linux.yml
      service: setup_template
    environment:
      TEST_NAME: *test_name
      TEST_TOKEN: *test_token

  app_test_user_rate_limiting_1_minute_enable_disable:
    extends:
      file: ../compose.templates.linux.yml
      service: app_template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: *test_token
      DATABASE_URL: *database_url
    depends_on:
      setup_test_user_rate_limiting_1_minute_enable_disable:
        condition: service_completed_successfully

  test_user_rate_limiting_1_minute_enable_disable:
    extends:
      file: ../compose.templates.linux.yml
      service: test_template
    environment:
      TEST_NAME: *test_name
      TEST_TOKEN: *test_token
      TEST_SERVER_HOST: *app_service
      TEST_CONTROL_SERVER_HOST: *app_service
    depends_on:
      app_test_user_rate_limiting_1_minute_enable_disable:
        condition: service_started
