services:
  app-test-aikido-disable:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: app-template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: AIK_RUNTIME_1_test-aikido-disable
      DATABASE_NAME: test-aikido-disable
      DATABASE_URL:
        '${DATABASE_URL_PREFIX:?Set
        DATABASE_URL_PREFIX}test-aikido-disable${DATABASE_URL_SUFFIX:?Set
        DATABASE_URL_SUFFIX}'
