services:
  control-test-restart:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: control-app-template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: AIK_RUNTIME_1_control-test-restart
      DATABASE_NAME: control-test-restart
      DATABASE_URL:
        '${DATABASE_URL_PREFIX:?Set
        DATABASE_URL_PREFIX}control-test-restart${DATABASE_URL_SUFFIX:?Set
        DATABASE_URL_SUFFIX}'
