services:
  app-control-test-kill-agent:
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: app-template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: AIK_RUNTIME_1_control-test-kill-agent
      DATABASE_NAME: control-test-kill-agent
      DATABASE_URL:
        '${DATABASE_URL_PREFIX:?Set
        DATABASE_URL_PREFIX}control-test-kill-agent${DATABASE_URL_SUFFIX:?Set
        DATABASE_URL_SUFFIX}'
