services:
  test-rate-limiting-retry-after:
    profiles:
      - policies
    extends:
      file: ../compose.templates.${COMPOSE_OS:?Set COMPOSE_OS}.yml
      service: app-template
    env_file:
      - ./test.env
    environment:
      AIKIDO_TOKEN: AIK_RUNTIME_1_test-rate-limiting-retry-after
      DATABASE_NAME: test-rate-limiting-retry-after
      DATABASE_URL:
        '${DATABASE_URL_PREFIX:?Set
        DATABASE_URL_PREFIX}test-rate-limiting-retry-after${DATABASE_URL_SUFFIX:?Set
        DATABASE_URL_SUFFIX}'
